package view;

import dao.ContaDAO;
import exception.SaldoInsuficienteException;
import model.ContaCorrente;
import service.ContaService;
import service.TarifaService;
import strategy.TarifaStrategy;

import java.io.IOException;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class ContaGUI extends javax.swing.JFrame {

    /**
     * Creates new form ContaGUI
     */
    private ContaCorrente conta;
    private ContaService contaService;
    private TarifaService tarifaService;
    private ContaDAO contaDAO;
    private boolean bancoDisponivel; // false = MySQL fora do ar, trabalha só com arquivo
    private DefaultTableModel modeloTabela;
    private List<ContaCorrente> contas;
    private List<ContaCorrente> contasExibidas; // lista atualmente mostrada na tabela (todas ou filtradas)
    private ContaCorrente contaSelecionada;

    public ContaGUI() {

        initComponents();
        carregarDados();

    }

    private void carregarDados() {
        contaService = new ContaService();
        tarifaService = new TarifaService();
        contaDAO = new ContaDAO();
        modeloTabela = (DefaultTableModel) tabelaContas.getModel();

        // Aula 05 - Tarefa 4: na inicialização as contas vêm do banco de dados
        try {
            contas = contaDAO.listar();
            bancoDisponivel = true;
            atualizarTabela(contas);
            txtAreaArquivo.append(contas.size() + " conta(s) carregada(s) do banco de dados!\n");
        } catch (SQLException e) {
            bancoDisponivel = false;
            JOptionPane.showMessageDialog(this,
                    "Não foi possível conectar ao banco de dados:\n" + e.getMessage()
                    + "\n\nO programa vai continuar usando o arquivo contas.txt."
                    + "\nVerifique o MySQL e os dados em dao/Conexao.java.",
                    "Banco indisponível", JOptionPane.WARNING_MESSAGE);
            carregarDoArquivo();
        }
    }

    // usado só quando o banco não está acessível (mantém as aulas 03 e 04 funcionando)
    private void carregarDoArquivo() {
        try {
            contas = contaService.carregarContas("contas.txt");
            atualizarTabela(contas);
            txtAreaArquivo.append(contas.size() + " conta(s) carregada(s) do arquivo contas.txt.\n");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Erro ao acessar arquivo: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            contas = new ArrayList<>();
            atualizarTabela(contas);
        }
    }

    // Aula 05 - Tarefa 4: grava no banco o saldo da conta após saque/depósito/tarifa
    private void persistirSaldo(ContaCorrente c) {
        if (!bancoDisponivel) {
            return;
        }
        try {
            contaDAO.atualizarSaldo(c.getNumero(), c.getSaldo());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar o saldo no banco: " + ex.getMessage(),
                    "Erro de banco", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizarTabela(List<ContaCorrente> lista) {
        contasExibidas = lista;
        modeloTabela.setRowCount(0);
        for (ContaCorrente c : lista) {
            modeloTabela.addRow(new Object[]{
                c.getNumero(), c.getTitular(), String.format("R$ %.2f", c.getSaldo())
            });
        }
        // mantém a conta selecionada marcada na tabela, se ela estiver sendo exibida
        int linha = lista.indexOf(contaSelecionada);
        if (linha >= 0) {
            tabelaContas.setRowSelectionInterval(linha, linha);
        }
    }

    private void exibirDetalhes(ContaCorrente c) {
        txtNumero.setText(String.valueOf(c.getNumero()));
        txtTitular.setText(c.getTitular());
        txtSaldo.setText(String.format("R$ %.2f", c.getSaldo()));
    }

    private void atualizarAposOperacao() {
        atualizarTabela(contas);
        if (contaSelecionada != null) {
            exibirDetalhes(contaSelecionada); // atualização automática do saldo na tela
        }
        try {
            contaService.salvarContas(contas, "contas_atualizadas.txt");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNumero = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblSaque = new javax.swing.JLabel();
        txtSaque = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaArquivo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaContas = new javax.swing.JTable();
        btnDepositar = new javax.swing.JButton();
        btnNovaConta = new javax.swing.JButton();
        btnFiltrarSaldoAlto = new javax.swing.JButton();
        btnMostrarTodas = new javax.swing.JButton();
        btnSaldoTotal = new javax.swing.JButton();
        btnAgruparFaixas = new javax.swing.JButton();
        btnFiltrarSaldo5000 = new javax.swing.JButton();
        btnFiltrarNumeroPar = new javax.swing.JButton();
        btnOrdenarSaldo = new javax.swing.JButton();
        btnOrdenarTitular = new javax.swing.JButton();
        btnAplicarTarifa = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        btnRecarregarBanco = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIADOR DE CONTA BANCÁRIA");

        lblNumero.setText("Número:");

        lblTitular.setText("Titular:");

        lblSaldo.setText("Saldo:");

        txtNumero.setEditable(false);

        txtTitular.setEditable(false);

        txtSaldo.setEditable(false);

        lblSaque.setText("Valor para saque:");

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        txtAreaArquivo.setEditable(false);
        txtAreaArquivo.setColumns(20);
        txtAreaArquivo.setRows(5);
        jScrollPane1.setViewportView(txtAreaArquivo);

        tabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Titular", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaContas);

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnNovaConta.setText("Nova Conta");
        btnNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaContaActionPerformed(evt);
            }
        });

        btnFiltrarSaldoAlto.setText("Contas > R$10000");
        btnFiltrarSaldoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarSaldoAltoActionPerformed(evt);
            }
        });

        btnMostrarTodas.setText("Mostrar Todas");
        btnMostrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodasActionPerformed(evt);
            }
        });

        btnSaldoTotal.setText("Saldo Total");
        btnSaldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoTotalActionPerformed(evt);
            }
        });

        btnAgruparFaixas.setText("Agrupar por Faixa");
        btnAgruparFaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgruparFaixasActionPerformed(evt);
            }
        });

        btnFiltrarSaldo5000.setText("Saldo > R$5000");
        btnFiltrarSaldo5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarSaldo5000ActionPerformed(evt);
            }
        });

        btnFiltrarNumeroPar.setText("Número Par");
        btnFiltrarNumeroPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarNumeroParActionPerformed(evt);
            }
        });

        btnOrdenarSaldo.setText("Ordenar por Saldo");
        btnOrdenarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarSaldoActionPerformed(evt);
            }
        });

        btnOrdenarTitular.setText("Ordenar por Titular");
        btnOrdenarTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarTitularActionPerformed(evt);
            }
        });

        btnAplicarTarifa.setText("Aplicar Tarifa");
        btnAplicarTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarTarifaActionPerformed(evt);
            }
        });

        btnExcluirConta.setText("Excluir Conta");
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });

        btnRecarregarBanco.setText("Recarregar do Banco");
        btnRecarregarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregarBancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addComponent(btnNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFiltrarSaldoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgruparFaixas, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFiltrarSaldo5000, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrarNumeroPar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrdenarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrdenarTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAplicarTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcluirConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecarregarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaque)
                            .addComponent(txtSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacar)
                    .addComponent(btnDepositar)
                    .addComponent(btnNovaConta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrarSaldoAlto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaldoTotal)
                            .addComponent(btnAgruparFaixas)))
                    .addComponent(btnMostrarTodas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrarSaldo5000)
                    .addComponent(btnFiltrarNumeroPar)
                    .addComponent(btnOrdenarSaldo)
                    .addComponent(btnOrdenarTitular)
                    .addComponent(btnAplicarTarifa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirConta)
                    .addComponent(btnRecarregarBanco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela.");
            return;
        }
        try {
            double valor = Double.parseDouble(txtSaque.getText().trim());
            contaService.sacarValor(contaSelecionada, valor);
            persistirSaldo(contaSelecionada); // UPDATE no banco
            txtAreaArquivo.append(String.format("Saque de R$ %.2f realizado na conta %d.\n",
                    valor, contaSelecionada.getNumero()));
            atualizarAposOperacao();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Informe um valor numérico válido.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SaldoInsuficienteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Saldo Insuficiente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela.");
            return;
        }
        try {
            double valor = Double.parseDouble(txtSaque.getText().trim());
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "O valor deve ser positivo.");
                return;
            }
            contaService.depositarValor(contaSelecionada, valor);
            persistirSaldo(contaSelecionada); // UPDATE no banco
            txtAreaArquivo.append(String.format("Depósito de R$ %.2f realizado na conta %d.\n",
                    valor, contaSelecionada.getNumero()));
            atualizarAposOperacao();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Informe um valor numérico válido.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnDepositarActionPerformed

    private void tabelaContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContasMouseClicked
        int linha = tabelaContas.getSelectedRow();
        if (linha < 0 || linha >= contasExibidas.size()) {
            return;
        }

        // usa a lista exibida, pois a tabela pode estar mostrando só as contas filtradas
        contaSelecionada = contasExibidas.get(linha);
        exibirDetalhes(contaSelecionada);
    }//GEN-LAST:event_tabelaContasMouseClicked

    private void btnNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaContaActionPerformed
        try {
            String numeroStr = JOptionPane.showInputDialog(this, "Número da conta:");
            if (numeroStr == null) {
                return;
            }
            String titular = JOptionPane.showInputDialog(this, "Titular:");
            if (titular == null) {
                return;
            }
            String saldoStr = JOptionPane.showInputDialog(this, "Saldo inicial:");
            if (saldoStr == null) {
                return;
            }

            int numero = Integer.parseInt(numeroStr.trim());
            double saldo = Double.parseDouble(saldoStr.trim());

            ContaCorrente nova = new ContaCorrente(numero, titular.trim(), saldo);

            // Aula 05 - Tarefa 4: INSERT no banco antes de guardar na coleção
            if (bancoDisponivel) {
                try {
                    contaDAO.inserir(nova);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Erro ao inserir no banco: " + ex.getMessage()
                            + "\n(o número da conta já existe?)",
                            "Erro de banco", JOptionPane.ERROR_MESSAGE);
                    return; // não adiciona na memória se falhou no banco
                }
            }

            contas.add(nova);
            txtAreaArquivo.append("Nova conta " + numero + " criada.\n");
            atualizarAposOperacao();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Número ou saldo inválido.");
        }    }//GEN-LAST:event_btnNovaContaActionPerformed

    private void btnFiltrarSaldoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarSaldoAltoActionPerformed
        // 15.1 - filtra com Streams as contas com saldo > R$ 10.000 e exibe na tabela
        List<ContaCorrente> filtradas = contaService.filtrarContasSaldoAlto(contas);
        atualizarTabela(filtradas);
        txtAreaArquivo.append(filtradas.size() + " conta(s) com saldo superior a R$ 10000.\n");
    }//GEN-LAST:event_btnFiltrarSaldoAltoActionPerformed

    private void btnMostrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodasActionPerformed
        atualizarTabela(contas);
        txtAreaArquivo.append("Exibindo todas as " + contas.size() + " conta(s).\n");
    }//GEN-LAST:event_btnMostrarTodasActionPerformed

    private void btnSaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoTotalActionPerformed
        // 15.2 - saldo total de todas as contas calculado com reduce()
        double saldoTotal = contaService.calcularSaldoTotal(contas);
        txtAreaArquivo.append(String.format("Saldo total das contas: R$ %.2f\n", saldoTotal));
        JOptionPane.showMessageDialog(this,
                String.format("Saldo total de todas as contas: R$ %.2f", saldoTotal),
                "Saldo Total", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaldoTotalActionPerformed

    private void btnAgruparFaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgruparFaixasActionPerformed
        // 15.3 - contas agrupadas por faixa de saldo com Collectors.groupingBy
        Map<String, List<ContaCorrente>> grupos = contaService.agruparPorFaixaSaldo(contas);

        StringBuilder sb = new StringBuilder();
        for (String faixa : ContaService.FAIXAS) {
            List<ContaCorrente> grupo = grupos.getOrDefault(faixa, new ArrayList<>());
            sb.append(faixa).append(" (").append(grupo.size()).append(" conta(s)):\n");
            for (ContaCorrente c : grupo) {
                sb.append(String.format("    %d - %s - R$ %.2f\n",
                        c.getNumero(), c.getTitular(), c.getSaldo()));
            }
        }

        txtAreaArquivo.append("Contas agrupadas por faixa de saldo:\n" + sb);
        JOptionPane.showMessageDialog(this, sb.toString(),
                "Contas por Faixa de Saldo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgruparFaixasActionPerformed

    private void btnFiltrarSaldo5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarSaldo5000ActionPerformed
        // Aula 04 - 11.1: Predicate como estratégia de filtro
        List<ContaCorrente> filtradas = contaService.filtrar(contas, ContaService.SALDO_MAIOR_5000);
        atualizarTabela(filtradas);
        txtAreaArquivo.append(filtradas.size() + " conta(s) com saldo maior que R$ 5000.\n");
    }//GEN-LAST:event_btnFiltrarSaldo5000ActionPerformed

    private void btnFiltrarNumeroParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarNumeroParActionPerformed
        // Aula 04 - 11.1: Predicate como estratégia de filtro
        List<ContaCorrente> filtradas = contaService.filtrar(contas, ContaService.NUMERO_PAR);
        atualizarTabela(filtradas);
        txtAreaArquivo.append(filtradas.size() + " conta(s) com número par.\n");
    }//GEN-LAST:event_btnFiltrarNumeroParActionPerformed

    private void btnOrdenarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarSaldoActionPerformed
        // Aula 04 - 11.2: Comparator como estratégia de ordenação
        contaService.ordenar(contas, ContaService.POR_SALDO_DECRESCENTE);
        atualizarTabela(contas);
        txtAreaArquivo.append("Contas ordenadas por saldo (decrescente).\n");
    }//GEN-LAST:event_btnOrdenarSaldoActionPerformed

    private void btnOrdenarTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarTitularActionPerformed
        // Aula 04 - 11.2: Comparator como estratégia de ordenação
        contaService.ordenar(contas, ContaService.POR_TITULAR);
        atualizarTabela(contas);
        txtAreaArquivo.append("Contas ordenadas por titular (A-Z).\n");
    }//GEN-LAST:event_btnOrdenarTitularActionPerformed

    private void btnAplicarTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarTarifaActionPerformed
        // Aula 04 - 12: enum TarifaStrategy escolhido em tempo de execução
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela.");
            return;
        }

        TarifaStrategy estrategia = (TarifaStrategy) JOptionPane.showInputDialog(this,
                "Escolha a estratégia de tarifa:", "Aplicar Tarifa",
                JOptionPane.QUESTION_MESSAGE, null, TarifaStrategy.values(), TarifaStrategy.FIXA);
        if (estrategia == null) {
            return; // usuário cancelou
        }

        double tarifa = tarifaService.calcularTarifa(contaSelecionada, estrategia);
        int opcao = JOptionPane.showConfirmDialog(this,
                String.format("Tarifa %s: R$ %.2f%nDescontar da conta %d?",
                        estrategia.name(), tarifa, contaSelecionada.getNumero()),
                "Aplicar Tarifa", JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            tarifaService.aplicarTarifa(contaSelecionada, estrategia);
            persistirSaldo(contaSelecionada); // UPDATE no banco
            txtAreaArquivo.append(String.format("Tarifa %s de R$ %.2f aplicada na conta %d.\n",
                    estrategia.name(), tarifa, contaSelecionada.getNumero()));
            atualizarAposOperacao();
        } catch (SaldoInsuficienteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Saldo Insuficiente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAplicarTarifaActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        // Aula 05 - Tarefa 4: DELETE no banco + remoção da coleção em memória
        if (contaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela.");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(this,
                "Excluir a conta " + contaSelecionada.getNumero()
                + " (" + contaSelecionada.getTitular() + ")?",
                "Excluir Conta", JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }

        if (bancoDisponivel) {
            try {
                contaDAO.remover(contaSelecionada.getNumero());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao remover do banco: " + ex.getMessage(),
                        "Erro de banco", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        txtAreaArquivo.append("Conta " + contaSelecionada.getNumero() + " excluída.\n");
        contas.remove(contaSelecionada);
        contaSelecionada = null;
        txtNumero.setText("");
        txtTitular.setText("");
        txtSaldo.setText("");
        atualizarAposOperacao();
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnRecarregarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregarBancoActionPerformed
        // Aula 05 - SELECT: recarrega a coleção em memória a partir do banco
        try {
            contas = contaDAO.listar();
            bancoDisponivel = true;
            contaSelecionada = null;
            atualizarTabela(contas);
            txtAreaArquivo.append(contas.size() + " conta(s) recarregada(s) do banco de dados.\n");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao ler o banco: " + ex.getMessage(),
                    "Erro de banco", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRecarregarBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ContaGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgruparFaixas;
    private javax.swing.JButton btnAplicarTarifa;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnFiltrarNumeroPar;
    private javax.swing.JButton btnFiltrarSaldo5000;
    private javax.swing.JButton btnFiltrarSaldoAlto;
    private javax.swing.JButton btnMostrarTodas;
    private javax.swing.JButton btnNovaConta;
    private javax.swing.JButton btnOrdenarSaldo;
    private javax.swing.JButton btnOrdenarTitular;
    private javax.swing.JButton btnRecarregarBanco;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSaldoTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaque;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JTable tabelaContas;
    private javax.swing.JTextArea txtAreaArquivo;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSaque;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
